export const GET_POKEMONS = "GET_POKEMONS"
export const POST_POKEMON = "POST_POKEMON"
export const DETAIL_POKEMON = "DETAIL_POKEMON"
export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID"
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME"


